version: '3'
services:
  cloudflared: 
    image: cloudflare/cloudflared 
    container_name: cloudflare-tunnel 
    env_file: ./tunnel.env
    restart: unless-stopped 
    command: tunnel run 

  nginxpm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginxpm
    restart: unless-stopped
    ports:
      # Public HTTP Port:
      - '80:80'
      # Public HTTPS Port:
      - '443:443'
      # Admin Web Port:
      - '81:81'
    volumes:
      - /opt/nginx-proxy-manager/data:/data
      - /opt/letsencrypt:/etc/letsencrypt

  homeassistant:
    image: k/homeassistant
    container_name: homeassistant
    build: .
    volumes:
      - /opt/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /dev/serial/by-id:/dev/serial/by-id
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      - TZ=Europe/London
    restart: unless-stopped

networks:
  default:
    external: true
    name: exposed
